name: validate

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: ./Scripts/test.sh
      - run: node esbuild.config.mjs production
